apiVersion: v1
name: scm-manager
version: 0.1.0
description: The easiest way to share and manage your Git, Mercurial and Subversion repositories

home: https://scm-manager.org
icon: https://raw.githubusercontent.com/scm-manager/scm-manager/2.7.0/docs/en/logo/scm-manager_logo_img.png

keywords:
- git
- mercurial
- hg
- subversion
- svn
- plugins
- scm
- vcs

maintainers:
- name: Sebastian Sdorra
  url: https://github.com/sdorra
  email: sebastian.sdorra@cloudogu.com
- name: René Pfeuffer
  url: https://github.com/pfeuffer
  email: rene.pfeuffer@cloudogu.com
- name: Eduard Heimbuch
  url: https://github.com/eheimbuch
  email: eduard.heimbuch@cloudogu.com 
